sudo apt-get install clang 
sudo apt-get install cscope
sudo apt-get install python-dev
sudo apt-get install python-virtualenv
#sudo apt-get install ttf-incon...     
sudo apt-get install automake 
sudo apt-get install libxml2-dev
sudo apt-get install texinfo
sudo apt-get install fonts-inconsolata
